name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install  # 改用 npm install 替代 npm ci

    - name: Build extension
      run: npm run build
      env:
        NODE_ENV: production

    - name: Create output directories
      run: |
        mkdir -p dist/popup
        mkdir -p dist/background
        mkdir -p dist/content
        mkdir -p dist/pages/feedback
        mkdir -p dist/pages/permission

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../extension.zip ./*

    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: extension.zip

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: extension.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}