name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: |
        npm run clean
        npm run build
      env:
        NODE_ENV: production

    - name: Prepare extension files
      run: |
        mkdir -p dist/popup
        mkdir -p dist/background
        mkdir -p dist/content
        mkdir -p dist/pages/feedback
        mkdir -p dist/pages/permission
        mkdir -p dist/services
        mkdir -p dist/utils
        
        # 复制必要文件
        cp manifest.json dist/
        cp -r assets dist/
        
        # 复制 HTML 和 CSS 文件
        cp src/popup/popup.html dist/popup/
        cp src/popup/popup.css dist/popup/
        
        # 复制其他必要的页面文件
        cp src/pages/feedback/feedback.html dist/pages/feedback/
        cp src/pages/feedback/feedback.css dist/pages/feedback/
        cp src/pages/permission/index.html dist/pages/permission/

        # 打印目录结构以便调试
        tree dist/

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../extension.zip ./*

    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: extension.zip

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: extension.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}