name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: |
        npm run clean
        npm run build
      env:
        NODE_ENV: production

    - name: Prepare extension files
      run: |
        mkdir -p dist
        cp manifest.json dist/
        cp -r assets dist/
        cp src/popup/popup.html dist/popup/
        cp src/popup/popup.css dist/popup/

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../extension.zip ./*

    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: extension.zip

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: extension.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}